In [1]:
# varshini A

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [5]:
value=np.array([20,30,40,50,60])
print(value)

[20 30 40 50 60]


In [6]:
value=np.array([15,16,17,18,19])
print("Numpy array:")
print(value)

Numpy array:
[15 16 17 18 19]


In [17]:
print("/nShape of numpy array:")
print(value.shape)

/nShape of numpy array:
(5,)


In [9]:
import pandas as pd

In [20]:
value=pd.Series([20,30,40,50,60])
print(value)

0    20
1    30
2    40
3    50
4    60
dtype: int64


In [22]:
value=np.array([1,2,3,4,5,6,7,8,9,5])
print("/n 1Dimensional Numpy array:")
print(value)

/n 1Dimensional Numpy array:
[1 2 3 4 5 6 7 8 9 5]


In [24]:
value=np.array([23,45,67,23,58])
print("/n Multidemendional Numpy array:")
print(value)

/n Multidemendional Numpy array:
[23 45 67 23 58]


In [26]:
v=np.zeros((4,5))
v2=np.zeros(9)
print(v)
print(v2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [35]:
v =np.ones((5,4))
v2 =np.ones(9)
print(v)
print(v2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
